services:
  bazarr:
    image: linuxserver/bazarr:latest
    ports:
      - "16768:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - bazarr-config:/config
      - ./tests/fixtures/config.yaml:/config/config/config.yaml

volumes:
  bazarr-config:
